### ISSUE TITLE
Implement footer component

### ISSUE THREAD

**Issue by jnvo25** [fnyaung/CloudyHappiness#7]
<img width="242" alt="Screen Shot 2021-11-19 at 4 32 48 PM" src="https://user-images.githubusercontent.com/38309580/142707320-51f9db06-f5f2-4d04-818d-9f5aff55b007.png">

**Comment by Blibertore** [comment]
Completed visual look of footer

**Comment by Blibertore** [comment]
Needs to be tweaked for responsiveness
